language: python
python:
    - "2.7"

branches:
    only:
    - ng

before_script:
- "wget https://googleappengine.googlecode.com/files/google_appengine_${APPENGINE_SDK_VERSION}.zip -nv"
- "unzip -q google_appengine_${APPENGINE_SDK_VERSION}.zip"

env:
- APPENGINE_SDK_VERSION=1.8.2

install: pip install -r requirements.txt

script: PYTHONPATH=".:google_appengine" nosetests --with-gae --rednose