language: python
python:
- '2.7'
node_js:
- 0.10.13
ruby:
- 1.9.3-p429

install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- gem install sass
- ./install_assets_deps.sh
- grunt clean build

script:
- nosetests -c nose.cfg
- grunt test
