language: python
python:
    - "2.7"

branches:
    only:
    - ng

before_script:
- wget https://googleappengine.googlecode.com/files/google_appengine_1.8.2.zip -nv
- unzip -q google_appengine_1.8.2.zip

install: pip install -r requirements.txt

script: nosetests --with-gae --rednose