language: python
python:
- '2.7'
node_js:
- 0.10.13
ruby:
- 1.9.3-p429

env:
  matrix:
  - APPENGINE_SDK_VERSION=1.8.2
  global:
    - APPENGINE_SDK_PATH=./google_appengine
    - secure: NZpAQCwWfn5TqIGRA74mAdk6HrmUxtu6bFx8zbdLsBHOWnaipgR2DLUNRxqcOI2KeuKhbfJrVejcfGOHLp0tk34WlTxhBBcHpFH+XbjYQROOPcZNokeg9MdlhTIniu4OAlIB0RXfRVbkLeHLpUqPI/cdHT8BhcI1Z9hDx+KvUGI=

install:
- pip install -r requirements.txt
- gem install sass
- ./install_assets_deps.sh
- grunt build

before_script:
- unzip -q dependencies/google_appengine_${APPENGINE_SDK_VERSION}.zip

script:
- PYTHONPATH=".:$APPENGINE_SDK_PATH" nosetests --with-gae --rednose
- grunt test

after_success: ./deploy.sh
