language: python
python:
- '3.4'

node_js:
- 8.6.0

ruby:
- 1.9.3-p429

cache:
  yarn: true
  directories:
  - ui/node_modules

before_install:
# Workaround for a permissions issue with Travis virtual machine images
# that breaks Python's multiprocessing:
# https://github.com/travis-ci/travis-cookbooks/issues/155
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm

install:
# pip is not able to install distribute: "ImportError: No module named _markerlib"
- easy_install distribute
- pip install -qr requirements.txt
- pip install -qr requirements-dev.txt
- ./install_assets_deps.sh
- cd ui && yarn install

script:
- nosetests -c nose.cfg --verbosity=1
- cd ui && yarn test
